---
- name: Aplicar hardening de segurança Ubuntu 24.04
  hosts: servers        # definido em inventory.ini
  become: true          # executa as tarefas como root
  gather_facts: true

  vars_prompt:
    - name: deploy_password
      prompt: "Digite a senha para o usuário 'deploy' (será solicitada duas vezes)"
      private: yes
      confirm: yes

  pre_tasks:
    - name: Gerar hash SHA512 da senha do usuário deploy
      set_fact:
        deploy_password_hash: "{{ deploy_password | password_hash('sha512') }}"

  roles:
    - hardening_ubuntu 