---
# tasks/main.yml — Hardening Ubuntu 24.04
# Cada bloco corresponde às etapas aprovadas pelo usuário.
# Comentários extensivos explicam o propósito de cada tarefa.

- name: "ETAPA 1 | Adicionar repositório de segurança 'noble-security'"
  apt_repository:
    repo: "{{ security_repo }}"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_release == "noble"
  tags: [security, updates]

- name: "ETAPA 1 | Atualizar cache APT e atualizar pacotes (dist-upgrade)"
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600
  tags: [security, updates]

- name: "ETAPA 1 | Instalar pacotes de segurança e utilitários essenciais"
  apt:
    name:
      - ufw
      - fail2ban
      - auditd
      - audispd-plugins
      - sysstat
      - rkhunter
      - debsums
      - apt-listbugs
      - apt-listchanges
      - curl
      - jq
      - openssl
    state: present
  notify: reload ufw
  tags: [security, packages]

# --------------------------------------------------------------------
# ETAPA 2 – Criação do usuário de deploy com privilégios sudo
# --------------------------------------------------------------------
- name: "ETAPA 2 | Criar usuário '{{ new_user }}' com senha e grupo sudo"
  user:
    name: "{{ new_user }}"
    comment: "Deployment user"
    password: "{{ deploy_password_hash }}"
    groups: sudo
    append: yes
    shell: /bin/bash
    state: present
  tags: [user-management]

# --------------------------------------------------------------------
# ETAPA 3 – Configuração de swap e ajuste de swappiness
# --------------------------------------------------------------------
- name: "ETAPA 3 | Verificar se /swapfile já existe"
  stat:
    path: /swapfile
  register: swapfile_stat
  tags: [swap]

- name: "ETAPA 3 | Criar arquivo de swap"
  command: fallocate -l {{ swap_size }} /swapfile
  when: not swapfile_stat.stat.exists
  tags: [swap]

- name: "ETAPA 3 | Definir permissões para /swapfile"
  file:
    path: /swapfile
    mode: '0600'
  when: not swapfile_stat.stat.exists
  tags: [swap]

- name: "ETAPA 3 | Formatar /swapfile"
  command: mkswap /swapfile
  when: not swapfile_stat.stat.exists
  tags: [swap]

- name: "ETAPA 3 | Ativar swap"
  command: swapon /swapfile
  when: not swapfile_stat.stat.exists
  tags: [swap]

- name: "ETAPA 3 | Adicionar /swapfile ao /etc/fstab"
  mount:
    name: none
    src: /swapfile
    fstype: swap
    opts: sw
    state: present
  tags: [swap]

- name: "ETAPA 3 | Ajustar vm.swappiness para 10"
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    reload: yes
  tags: [swap]

# --------------------------------------------------------------------
# ETAPA 4 – Configuração do firewall UFW
# --------------------------------------------------------------------
- name: "ETAPA 4 | Definir política padrão: negar conexões de entrada"
  ufw:
    state: enabled
    direction: incoming
    policy: deny
  tags: [ufw, firewall]

- name: "ETAPA 4 | Definir política padrão: permitir conexões de saída"
  ufw:
    state: enabled
    direction: outgoing
    policy: allow
  tags: [ufw, firewall]

- name: "ETAPA 4 | Liberar portas necessárias no UFW"
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_allowed_ports }}"
  tags: [ufw, firewall]

# --------------------------------------------------------------------
# ETAPA 5 – Hardening do SSH
# --------------------------------------------------------------------
- name: "ETAPA 5 | Garantir 'Port 22' configurado"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port '
    line: 'Port 22'
    state: present
  tags: [ssh]

- name: "ETAPA 5 | Desabilitar login root via SSH"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin '
    line: 'PermitRootLogin no'
    state: present
  tags: [ssh]

- name: "ETAPA 5 | Garantir PasswordAuthentication habilitado"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication '
    line: 'PasswordAuthentication yes'
    state: present
  tags: [ssh]

- name: "ETAPA 5 | Inserir opções extras de hardening no sshd_config"
  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} ANSIBLE HARDENING"
    block: |
      LogLevel VERBOSE
      X11Forwarding no
      AllowAgentForwarding no
      AllowTcpForwarding no
      MaxAuthTries 3
      MaxSessions 2
      TCPKeepAlive no
  notify: reload sshd
  tags: [ssh]

- name: "ETAPA 5 | Validar sintaxe do sshd_config"
  command: sshd -t
  tags: [ssh]

# --------------------------------------------------------------------
# ETAPA 6 – Políticas de sistema / kernel
# --------------------------------------------------------------------
- name: "ETAPA 6 | Desabilitar core dumps para todos os usuários"
  copy:
    dest: /etc/security/limits.d/99-disable-coredumps.conf
    content: "* hard core 0\n"
    owner: root
    group: root
    mode: '0644'
  tags: [kernel, limits]

- name: "ETAPA 6 | Ajustar UMASK padrão para 027"
  lineinfile:
    path: /etc/login.defs
    regexp: '^UMASK'
    line: 'UMASK           027'
  tags: [kernel]

- name: "ETAPA 6 | Definir método de criptografia SHA512"
  lineinfile:
    path: /etc/login.defs
    regexp: '^ENCRYPT_METHOD'
    line: 'ENCRYPT_METHOD SHA512'
  tags: [kernel]

- name: "ETAPA 6 | Garantir SHA_CRYPT_MIN_ROUNDS 500000"
  lineinfile:
    path: /etc/login.defs
    line: 'SHA_CRYPT_MIN_ROUNDS 500000'
    insertafter: EOF
    state: present
  tags: [kernel]

- name: "ETAPA 6 | Bloquear protocolos em desuso"
  copy:
    dest: /etc/modprobe.d/99-disable-uncommon-net.conf
    content: |
      install dccp /bin/true
      install sctp /bin/true
      install rds /bin/true
      install tipc /bin/true
  tags: [kernel]

- name: "ETAPA 6 | Copiar banner legal para /etc/issue e /etc/issue.net"
  copy:
    src: banner.txt
    dest: "{{ item }}"
  loop:
    - /etc/issue
    - /etc/issue.net
  notify: reload sshd
  tags: [banner]

# --------------------------------------------------------------------
# ETAPA 7 – Configuração do auditd
# --------------------------------------------------------------------
- name: "ETAPA 7 | Copiar regras customizadas do auditd"
  copy:
    src: 99-custom.rules
    dest: /etc/audit/rules.d/99-custom.rules
  notify: reload auditd
  tags: [auditd]

# --------------------------------------------------------------------
# ETAPA 8 – Configuração do Fail2ban
# --------------------------------------------------------------------
- name: "ETAPA 8 | Copiar jail.local do Fail2ban (SSH)"
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: reload fail2ban
  tags: [fail2ban]

# --------------------------------------------------------------------
# ETAPA 9 – Configuração do rkhunter
# --------------------------------------------------------------------
- name: "ETAPA 9 | Atualizar assinaturas do rkhunter"
  command: rkhunter --update
  tags: [rkhunter]

- name: "ETAPA 9 | Gerar baseline inicial do rkhunter (uma vez)"
  command: rkhunter --propupd
  args:
    creates: /var/lib/rkhunter/db/rkhunter.dat
  tags: [rkhunter]

- name: "ETAPA 9 | Agendar verificação semanal do rkhunter (segunda 03h00)"
  cron:
    name: "Weekly rkhunter scan"
    user: root
    minute: "0"
    hour: "3"
    weekday: "1"
    job: "/usr/bin/rkhunter --check --cronjob --report-warnings-only"
  tags: [rkhunter]

# --------------------------------------------------------------------
# ETAPA 10 – Configuração de fuso horário e NTP
# --------------------------------------------------------------------
- name: "ETAPA 10 | Instalar pacote(s) NTP (chrony)"
  apt:
    name: "{{ ntp_packages }}"
    state: present
  tags: [ntp]

- name: "ETAPA 10 | Definir fuso horário para {{ timezone }}"
  community.general.timezone:
    name: "{{ timezone }}"
  tags: [timezone]

- name: "ETAPA 10 | Garantir serviço chrony habilitado e rodando"
  service:
    name: chrony
    state: started
    enabled: yes
  when: "'chrony' in ntp_packages"
  tags: [ntp] 