---
# Handlers para reiniciar/recarregar serviços quando arquivos de configuração mudarem

- name: reload sshd
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: reload ufw
  community.general.ufw:
    state: reloaded

- name: reload auditd
  ansible.builtin.command: augenrules --load && systemctl restart auditd
  become: true

- name: reload fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted 